# ============================================================
# CORRECTIONS QC — SOMEC_20251106
# Generated by interactive_mission_qc_console.R
# ============================================================

# ============================================================
# OPENING — load data
# ============================================================

library(tidyverse)
library(janitor)
library(RODBC)

# Resolve repo root
.repo_root <- tryCatch({
  frames <- sys.frames()
  ofiles <- Filter(Negate(is.null), lapply(frames, function(f) f$ofile))
  if (length(ofiles) > 0) dirname(normalizePath(ofiles[[1]], mustWork = TRUE))
  else dirname(normalizePath(rstudioapi::getSourceEditorContext()$path, mustWork = TRUE))
}, error = function(e) getwd())

.cache_dir <- file.path(.repo_root, "GlobalContext", "_cache")

missions     <- readRDS(file.path(.cache_dir, "missions.rds"))
transects    <- readRDS(file.path(.cache_dir, "transects.rds"))
observations <- readRDS(file.path(.cache_dir, "observations.rds"))

cat("\u2705 Data loaded from cache.\n")

# ============================================================
# FIXES
# ============================================================






# ============================================================

# ── AVI090806 | UNKNOWN_CATALOG | transects$site [2026-03-24 09:46] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# CLOSING — save updated RDS + create new accdb (Windows only)
# ============================================================

saveRDS(missions,     file.path(.cache_dir, "missions.rds"))
saveRDS(transects,    file.path(.cache_dir, "transects.rds"))
saveRDS(observations, file.path(.cache_dir, "observations.rds"))
cat("\u2705 Updated RDS files saved.\n")

if (.Platform$OS.type == "windows") {
  .gestion_root <- dirname(.repo_root)
  .somec_root   <- dirname(.gestion_root)
  .accdb_src    <- file.path(.somec_root, "BaseDeDonnees", "SOMEC_20251106.accdb")
  .accdb_dst    <- file.path(.somec_root, "BaseDeDonnees", "SOMEC_20260324.accdb")
  file.copy(.accdb_src, .accdb_dst, overwrite = FALSE)
  con <- RODBC::odbcConnectAccess2007(.accdb_dst, believeNRows = FALSE)
  RODBC::sqlSave(con, missions,     tablename = "missions",     rownames = FALSE, append = FALSE)
  RODBC::sqlSave(con, transects,    tablename = "transects",    rownames = FALSE, append = FALSE)
  RODBC::sqlSave(con, observations, tablename = "observations", rownames = FALSE, append = FALSE)
  RODBC::odbcClose(con)
  cat("\u2705 New accdb created: SOMEC_20260324.accdb\n")
} else {
  cat("\u26a0\ufe0f  Run on Windows to create the new .accdb file.\n")
}
