# ============================================================
# QC FIXES — SOMEC_20251106
# Generated by interactive_mission_qc_console.R
# ============================================================

# ============================================================
# OPENING — load data
# ============================================================

library(tidyverse)
library(janitor)
library(RODBC)

# Resolve repo root
.repo_root <- tryCatch({
  frames <- sys.frames()
  ofiles <- Filter(Negate(is.null), lapply(frames, function(f) f$ofile))
  if (length(ofiles) > 0) dirname(normalizePath(ofiles[[1]], mustWork = TRUE))
  else dirname(normalizePath(rstudioapi::getSourceEditorContext()$path, mustWork = TRUE))
}, error = function(e) getwd())

.cache_dir <- file.path(.repo_root, "GlobalContext", "_cache")

missions     <- readRDS(file.path(.cache_dir, "missions.rds"))
transects    <- readRDS(file.path(.cache_dir, "transects.rds"))
observations <- readRDS(file.path(.cache_dir, "observations.rds"))

cat("\u2705 Data loaded from cache.\n")

# ============================================================
# FIXES
# ============================================================


# ── AVI090806 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-23 12:57] ──
# NA decision [vagues]: Replace with median (0.5)
transects <- transects |>
  mutate(
    vagues = if_else(mission == "AVI090806" & is.na(vagues),
      0.5, vagues)
  )

# ── AVI090806 | UNKNOWN_CATALOG | transects$site [2026-03-23 12:57] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )
