# ============================================================
# CORRECTIONS QC — NA
# Generated by interactive_mission_qc_console.R
# ============================================================

# ============================================================
# OPENING — load data
# ============================================================

library(tidyverse)
library(janitor)
library(RODBC)

# Resolve repo root
.repo_root <- tryCatch({
  frames <- sys.frames()
  ofiles <- Filter(Negate(is.null), lapply(frames, function(f) f$ofile))
  if (length(ofiles) > 0) dirname(normalizePath(ofiles[[1]], mustWork = TRUE))
  else dirname(normalizePath(rstudioapi::getSourceEditorContext()$path, mustWork = TRUE))
}, error = function(e) getwd())

.cache_dir <- file.path(.repo_root, "GlobalContext", "_cache")

missions     <- readRDS(file.path(.cache_dir, "missions.rds"))
transects    <- readRDS(file.path(.cache_dir, "transects.rds"))
observations <- readRDS(file.path(.cache_dir, "observations.rds"))

cat("✅ Data loaded from cache.\n")

# ============================================================
# FIXES
# ============================================================


# ── COR191022 | UNKNOWN_CATALOG | transects$site [2026-03-30 10:51] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )
