# ============================================================
# QC FIXES — SOMEC_20251106
# Generated by interactive_mission_qc_console.R
# ============================================================

# # Load data before running fixes:
# source("interactive_mission_qc_console.R")

# ============================================================
# FIXES
# ============================================================


# ── AVI090806 | UNKNOWN_CATALOG | transects$site [2026-03-26 16:39] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── AVI090806 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-26 16:44] ──
# NA decision [vagues]: Replace with median (0.5)
transects <- transects |>
  mutate(
    vagues = if_else(mission == "AVI090806" & is.na(vagues),
      0.5, vagues)
  )

# ============================================================

# ── AVI090806 | UNKNOWN_CATALOG | transects$site [2026-03-26 16:45] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# CLOSING — save updated RDS + create new accdb (Windows only)
# ============================================================

saveRDS(missions,     file.path(.cache_dir, "missions.rds"))
saveRDS(transects,    file.path(.cache_dir, "transects.rds"))
saveRDS(observations, file.path(.cache_dir, "observations.rds"))
cat("\u2705 Updated RDS files saved.\n")

if (.Platform$OS.type == "windows") {
  .gestion_root <- dirname(.repo_root)
  .somec_root   <- dirname(.gestion_root)
  .accdb_src    <- file.path(.somec_root, "BaseDeDonnees", "SOMEC_20251106.accdb")
  .accdb_dst    <- file.path(.somec_root, "BaseDeDonnees", "SOMEC_20260326.accdb")
  file.copy(.accdb_src, .accdb_dst, overwrite = FALSE)
  con <- RODBC::odbcConnectAccess2007(.accdb_dst, believeNRows = FALSE)
  RODBC::sqlSave(con, missions,     tablename = "missions",     rownames = FALSE, append = FALSE)
  RODBC::sqlSave(con, transects,    tablename = "transects",    rownames = FALSE, append = FALSE)
  RODBC::sqlSave(con, observations, tablename = "observations", rownames = FALSE, append = FALSE)
  RODBC::odbcClose(con)
  cat("\u2705 New accdb created: SOMEC_20260326.accdb\n")
} else {
  cat("\u26a0\ufe0f  Run on Windows to create the new .accdb file.\n")
}
