# ============================================================
# CORRECTIONS QC — SOMEC_20251106
# Generated by interactive_mission_qc_console.R
# ============================================================

# ============================================================
# OPENING — load data
# ============================================================

library(tidyverse)
library(janitor)
library(RODBC)

# Resolve repo root
.repo_root <- tryCatch({
  frames <- sys.frames()
  ofiles <- Filter(Negate(is.null), lapply(frames, function(f) f$ofile))
  if (length(ofiles) > 0) dirname(normalizePath(ofiles[[1]], mustWork = TRUE))
  else dirname(normalizePath(rstudioapi::getSourceEditorContext()$path, mustWork = TRUE))
}, error = function(e) getwd())

.cache_dir <- file.path(.repo_root, "GlobalContext", "_cache")

missions     <- readRDS(file.path(.cache_dir, "missions.rds"))
transects    <- readRDS(file.path(.cache_dir, "transects.rds"))
observations <- readRDS(file.path(.cache_dir, "observations.rds"))

cat("✅ Data loaded from cache.\n")

# ============================================================
# FIXES
# ============================================================


# ── COR191022 | UNKNOWN_CATALOG | transects$site [2026-03-30 11:15] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── COR191022 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-30 11:15] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── COR191022 | UNKNOWN_CATALOG | transects$int_exterieur [2026-03-30 11:16] ──
transects <- transects |>
  mutate(
    int_exterieur = case_when(
      int_exterieur == "Intérieur" ~ "Interieur",
      TRUE ~ int_exterieur
    )
  )

# ── COR191022 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-30 11:16] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "COR191022" &
      (heure < as.POSIXct("2019-10-22 00:00:00") |
       heure > as.POSIXct("2019-11-17 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── COR191022 | UNKNOWN_CATALOG | observations$activite [2026-03-30 11:17] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── COR191022 | UNKNOWN_CATALOG | observations$sexe [2026-03-30 11:17] ──
observations <- observations |>
  mutate(
    sexe = case_when(
      sexe == "Male" ~ "M",
      sexe == "Femelle" ~ "F",
      TRUE ~ sexe
    )
  )

# ── COR191022 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-30 11:19] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "COR191022" &
      (heure < as.POSIXct("2019-10-22 00:00:00") |
       heure > as.POSIXct("2019-11-17 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── COR191022 | CV_R6 | observations$R6 [2026-03-30 11:22] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission COR191022)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "COR191022" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL190526 | UNKNOWN_CATALOG | transects$site [2026-03-30 11:24] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Debut" ~ "début",
      site == "Fin" ~ "fin",
      site == "Début" ~ "début",
      TRUE ~ site
    )
  )

# ── TEL190526 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-30 11:24] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── TEL190526 | UNKNOWN_CATALOG | transects$int_exterieur [2026-03-30 11:25] ──
transects <- transects |>
  mutate(
    int_exterieur = case_when(
      int_exterieur == "Intérieur" ~ "Interieur",
      TRUE ~ int_exterieur
    )
  )

# ── TEL190526 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-30 11:25] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL190526" &
      (heure < as.POSIXct("2019-05-26 00:00:00") |
       heure > as.POSIXct("2019-06-14 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL190526 | UNKNOWN_CATALOG | observations$activite [2026-03-30 11:27] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      activite == "Navire" ~ "NAVIRE",
      TRUE ~ activite
    )
  )

# ── TEL190526 | UNKNOWN_CATALOG | observations$age [2026-03-30 11:27] ──
observations <- observations |>
  mutate(
    age = case_when(
      age == "Juvénile" ~ "Juvenile",
      TRUE ~ age
    )
  )

# ── TEL190526 | UNKNOWN_CATALOG | observations$plumage [2026-03-30 11:28] ──
observations <- observations |>
  mutate(
    plumage = case_when(
      plumage == "Forme claire" ~ "Forme Claire",
      plumage == "forme claire" ~ "Forme Claire",
      TRUE ~ plumage
    )
  )

# ── TEL190526 | UNKNOWN_CATALOG | observations$sexe [2026-03-30 11:28] ──
observations <- observations |>
  mutate(
    sexe = case_when(
      sexe == "Male" ~ "M",
      sexe == "Femelle" ~ "F",
      TRUE ~ sexe
    )
  )

# ── TEL190526 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-30 11:28] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL190526" &
      (heure < as.POSIXct("2019-05-26 00:00:00") |
       heure > as.POSIXct("2019-06-14 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL190526 | CV_R4 | observations$R4 [2026-03-30 11:30] ──
# R4 -- inspect rows with missing distance data (mission TEL190526)
observations |> filter(mission == "TEL190526", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── TEL190526 | CV_R6 | observations$R6 [2026-03-30 11:31] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL190526)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL190526" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL190526 | CV_R7 | observations$R7 [2026-03-30 11:32] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission TEL190526)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL190526" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── TEL190526 | CV_R10 | transects$R10 [2026-03-30 11:33] ──
# R10 -- targeted inspection (mission TEL190526)
transects |> filter(mission == "TEL190526", id_transect %in% c(4, 5, 6)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── TEL190906 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-30 12:27] ──
# NA decision [vagues]: Remplacer par la médiane (0.5)
transects <- transects |>
  mutate(
    vagues = if_else(mission == "TEL190906" & is.na(vagues),
      0.5, vagues)
  )

# ── TEL190906 | DIRECTION_RANGE_OUTLIER | transects$dir_vent [2026-03-30 12:28] ──
transects <- transects |>
  mutate(
    dir_vent = dir_vent  # décision du réviseur
  )

# ── TEL190906 | UNKNOWN_CATALOG | transects$site [2026-03-30 12:28] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Debut" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── TEL190906 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-30 12:28] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── TEL190906 | UNKNOWN_CATALOG | transects$int_exterieur [2026-03-30 12:28] ──
transects <- transects |>
  mutate(
    int_exterieur = case_when(
      int_exterieur == "Intérieur" ~ "Interieur",
      TRUE ~ int_exterieur
    )
  )

# ── TEL190906 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-30 12:28] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL190906" &
      (heure < as.POSIXct("2019-09-06 00:00:00") |
       heure > as.POSIXct("2019-10-01 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL190906 | UNKNOWN_CATALOG | observations$activite [2026-03-30 12:29] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      activite == "Vol" ~ "VOL",
      activite == "Navire" ~ "NAVIRE",
      TRUE ~ activite
    )
  )

# ── TEL190906 | UNKNOWN_CATALOG | observations$age [2026-03-30 12:30] ──
observations <- observations |>
  mutate(
    age = case_when(
      age == "Juvénile" ~ "Juvenile",
      age == "immature" ~ "Immature",
      TRUE ~ age
    )
  )

# ── TEL190906 | UNKNOWN_CATALOG | observations$sexe [2026-03-30 12:30] ──
observations <- observations |>
  mutate(
    sexe = case_when(
      sexe == "Femelle" ~ "F",
      sexe == "Male" ~ "M",
      TRUE ~ sexe
    )
  )

# ── TEL190906 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-30 12:30] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL190906" &
      (heure < as.POSIXct("2019-09-06 00:00:00") |
       heure > as.POSIXct("2019-10-01 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL190906 | CV_R3 | observations$R3 [2026-03-30 12:31] ──
# R3 -- inspect rows with missing nb_individu or activite (mission TEL190906)
observations |> filter(mission == "TEL190906", id %in% c()) |>
  select(id, date, heure, code_espece, nb_individu, activite, snapshot, in_transect)

# Fix example — set nb_individu to 1 where missing (adjust as needed):
# observations <- observations |>
#   mutate(nb_individu = if_else(
#     mission == "TEL190906" & id %in% c() & is.na(nb_individu), 1L, nb_individu))


# ── TEL190906 | CV_R4 | observations$R4 [2026-03-30 12:33] ──
# R4 -- inspect rows with missing distance data (mission TEL190906)
observations |> filter(mission == "TEL190906", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── TEL190906 | CV_R6 | observations$R6 [2026-03-30 12:33] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL190906)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL190906" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL190906 | CV_R7 | observations$R7 [2026-03-30 12:34] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission TEL190906)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL190906" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── TEL190906 | CV_R10 | transects$R10 [2026-03-30 12:34] ──
# R10 -- targeted inspection (mission TEL190906)
transects |> filter(mission == "TEL190906", id_transect %in% c(83, 90, 127)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── TEL120802 | UNKNOWN_CATALOG | transects$site [2026-03-30 12:37] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── TEL120802 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-30 12:37] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── TEL120802 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-30 12:37] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL120802" &
      (heure < as.POSIXct("2012-08-02 00:00:00") |
       heure > as.POSIXct("2012-08-31 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL120802 | UNKNOWN_CATALOG | observations$activite [2026-03-30 12:39] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      activite == "Navire" ~ "NAVIRE",
      activite == "Vol" ~ "VOL",
      TRUE ~ activite
    )
  )

# ── TEL120802 | UNKNOWN_CATALOG | observations$snapshot [2026-03-30 12:39] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── TEL120802 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-30 12:39] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL120802" &
      (heure < as.POSIXct("2012-08-02 00:00:00") |
       heure > as.POSIXct("2012-08-31 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL120802 | CV_R6 | observations$R6 [2026-03-30 12:40] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL120802)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL120802" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL120802 | CV_R10 | transects$R10 [2026-03-30 12:41] ──
# R10 -- targeted inspection (mission TEL120802)
transects |> filter(mission == "TEL120802", id_transect %in% c(21568, 21574, 21637, 21651, 21784, 22058, 22153)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── TEL120905 | NUMERIC_OUTLIER_NA | transects$vit_plateforme [2026-03-30 12:43] ──
# NA decision [vit_plateforme]: Valeur personnalisée = 11.3
transects <- transects |>
  mutate(
    vit_plateforme = if_else(mission == "TEL120905" & is.na(vit_plateforme),
      11.3, vit_plateforme)
  )

# ── TEL120905 | UNKNOWN_CATALOG | transects$site [2026-03-30 12:45] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── TEL120905 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-30 12:46] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── TEL120905 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-30 12:46] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL120905" &
      (heure < as.POSIXct("2012-09-05 00:00:00") |
       heure > as.POSIXct("2012-09-17 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL120905 | UNKNOWN_CATALOG | observations$activite [2026-03-30 12:46] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      activite == "Navire" ~ "NAVIRE",
      TRUE ~ activite
    )
  )

# ── TEL120905 | UNKNOWN_CATALOG | observations$snapshot [2026-03-30 12:47] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── TEL120905 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-30 12:47] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL120905" &
      (heure < as.POSIXct("2012-09-05 00:00:00") |
       heure > as.POSIXct("2012-09-17 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL120905 | CV_R4 | observations$R4 [2026-03-30 12:48] ──
# R4 -- inspect rows with missing distance data (mission TEL120905)
observations |> filter(mission == "TEL120905", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── TEL120905 | CV_R6 | observations$R6 [2026-03-30 12:49] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL120905)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL120905" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL120905 | CV_R7 | observations$R7 [2026-03-30 12:49] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission TEL120905)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL120905" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── TEL120905 | CV_R10 | transects$R10 [2026-03-30 12:50] ──
# R10 -- targeted inspection (mission TEL120905)
transects |> filter(mission == "TEL120905", id_transect %in% c(22475)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── TEL120919 | UNKNOWN_CATALOG | transects$site [2026-03-30 12:52] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── TEL120919 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-30 12:52] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── TEL120919 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-30 12:52] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL120919" &
      (heure < as.POSIXct("2012-09-19 00:00:00") |
       heure > as.POSIXct("2012-09-26 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL120919 | UNKNOWN_CATALOG | observations$activite [2026-03-30 12:53] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Navire" ~ "NAVIRE",
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── TEL120919 | UNKNOWN_CATALOG | observations$snapshot [2026-03-30 12:53] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── TEL120919 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-30 12:53] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL120919" &
      (heure < as.POSIXct("2012-09-19 00:00:00") |
       heure > as.POSIXct("2012-09-26 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL120919 | CV_R6 | observations$R6 [2026-03-30 12:54] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL120919)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL120919" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL120919 | CV_R10 | transects$R10 [2026-03-30 12:55] ──
# R10 -- targeted inspection (mission TEL120919)
transects |> filter(mission == "TEL120919", id_transect %in% c(22592)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── TEL130602 | NUMERIC_OUTLIER_NA | transects$visibilite [2026-03-30 12:56] ──
# NA decision [visibilite]: Remplacer par la médiane (20)
transects <- transects |>
  mutate(
    visibilite = if_else(mission == "TEL130602" & is.na(visibilite),
      20, visibilite)
  )

# ── TEL130602 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-30 12:57] ──
# NA decision [vagues]: Remplacer par la médiane (0.5)
transects <- transects |>
  mutate(
    vagues = if_else(mission == "TEL130602" & is.na(vagues),
      0.5, vagues)
  )

# ── TEL130602 | UNKNOWN_CATALOG | transects$site [2026-03-30 12:58] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── TEL130602 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-30 12:58] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── TEL130602 | UNKNOWN_CATALOG_NA | transects$act_plateforme [2026-03-30 12:58] ──
# Décision NA [act_plateforme]: Valeur personnalisée = Endéplacement
transects <- transects |>
  mutate(
    act_plateforme = if_else(mission == "TEL130602" & is.na(act_plateforme),
      "Endéplacement", act_plateforme)
  )

# ── TEL130602 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-30 12:59] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL130602" &
      (heure < as.POSIXct("2013-06-02 00:00:00") |
       heure > as.POSIXct("2013-06-21 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL130602 | UNKNOWN_CATALOG | observations$code_espece [2026-03-30 13:00] ──
observations <- observations |>
  mutate(
    code_espece = case_when(
      code_espece == "gupp" ~ "ALHC",
      code_espece == "guma" ~ "ALHC",
      code_espece == "fubo" ~ "ALHC",
      code_espece == "gubr" ~ "ALHC",
      code_espece == "occb" ~ "ALHC",
      code_espece == "ocsp" ~ "ALHC",
      TRUE ~ code_espece
    )
  )

# ── TEL130602 | UNKNOWN_CATALOG | observations$activite [2026-03-30 13:00] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── TEL130602 | UNKNOWN_CATALOG | observations$snapshot [2026-03-30 13:00] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── TEL130602 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-30 13:00] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL130602" &
      (heure < as.POSIXct("2013-06-02 00:00:00") |
       heure > as.POSIXct("2013-06-21 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL130602 | CV_R2 | observations$R2 [2026-03-30 13:02] ──
# R2 -- clear non-NA fields where code_espece = RIEN (mission TEL130602)
observations <- observations |>
  mutate(across(
    c("nb_individu", "activite", "tra_rad", "dis_rad", "tra_par", "dis_par", "association", "comportement", "direction", "dir_heure", "age", "plumage", "sexe"),
    ~ if_else(mission == "TEL130602" &
      str_to_upper(str_trim(code_espece)) == "RIEN", NA, .)
  ))


# ── TEL130602 | CV_R3 | observations$R3 [2026-03-30 13:02] ──
# R3 -- inspect rows with missing nb_individu or activite (mission TEL130602)
observations |> filter(mission == "TEL130602", id %in% c()) |>
  select(id, date, heure, code_espece, nb_individu, activite, snapshot, in_transect)

# Fix example — set nb_individu to 1 where missing (adjust as needed):
# observations <- observations |>
#   mutate(nb_individu = if_else(
#     mission == "TEL130602" & id %in% c() & is.na(nb_individu), 1L, nb_individu))


# ── TEL130602 | CV_R4 | observations$R4 [2026-03-30 13:02] ──
# R4 -- inspect rows with missing distance data (mission TEL130602)
observations |> filter(mission == "TEL130602", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── TEL130602 | CV_R5 | observations$R5 [2026-03-30 13:03] ──
# R5 fix: copy _rad -> _par where _par is missing, then clear _rad (mission TEL130602)
observations <- observations |>
  mutate(
    tra_par = if_else(
      mission == "TEL130602" & is.na(tra_par) & !is.na(tra_rad),
      tra_rad, tra_par),
    dis_par = if_else(
      mission == "TEL130602" & is.na(dis_par) & !is.na(dis_rad),
      dis_rad, dis_par),
    tra_rad = if_else(mission == "TEL130602", NA_real_, tra_rad),
    dis_rad = if_else(mission == "TEL130602", NA_real_, dis_rad)
  )


# ── TEL130602 | CV_R6 | observations$R6 [2026-03-30 13:03] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL130602)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL130602" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL130602 | CV_R7 | observations$R7 [2026-03-30 13:04] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission TEL130602)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL130602" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── TEL130602 | CV_R10 | transects$R10 [2026-03-30 13:04] ──
# R10 -- targeted inspection (mission TEL130602)
transects |> filter(mission == "TEL130602", id_transect %in% c(23174, 23177, 23180, 23281)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)

