# ============================================================
# CORRECTIONS QC — SOMEC_20251106
# Generated by interactive_mission_qc_console.R
# ============================================================

# ============================================================
# OPENING — load data
# ============================================================

library(tidyverse)
library(janitor)
library(RODBC)

# Resolve repo root
.repo_root <- tryCatch({
  frames <- sys.frames()
  ofiles <- Filter(Negate(is.null), lapply(frames, function(f) f$ofile))
  if (length(ofiles) > 0) dirname(normalizePath(ofiles[[1]], mustWork = TRUE))
  else dirname(normalizePath(rstudioapi::getSourceEditorContext()$path, mustWork = TRUE))
}, error = function(e) getwd())

.cache_dir <- file.path(.repo_root, "GlobalContext", "_cache")

missions     <- readRDS(file.path(.cache_dir, "missions.rds"))
transects    <- readRDS(file.path(.cache_dir, "transects.rds"))
observations <- readRDS(file.path(.cache_dir, "observations.rds"))

cat("\u2705 Data loaded from cache.\n")

# ============================================================
# FIXES
# ============================================================


# ── AVI090806 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-27 07:45] ──
# NA decision [vagues]: Remplacer par la médiane (0.5)
transects <- transects |>
  mutate(
    vagues = if_else(mission == "AVI090806" & is.na(vagues),
      0.5, vagues)
  )

# ── AVI090806 | UNKNOWN_CATALOG | transects$site [2026-03-27 07:47] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── AVI090806 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 07:47] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── AVI090806 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 07:48] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "AVI090806" &
      (heure < as.POSIXct("2009-08-06 00:00:00") |
       heure > as.POSIXct("2009-08-07 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── AVI090806 | UNKNOWN_CATALOG_RECODE | observations$activite [2026-03-27 07:51] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── AVI090806 | CV_R5 | observations$R5 [2026-03-27 07:56] ──
# R5 fix: copy _rad -> _par where _par is missing, then clear _rad (mission AVI090806)
observations <- observations |>
  mutate(
    tra_par = if_else(
      mission == "AVI090806" & is.na(tra_par) & !is.na(tra_rad),
      tra_rad, tra_par),
    dis_par = if_else(
      mission == "AVI090806" & is.na(dis_par) & !is.na(dis_rad),
      dis_rad, dis_par),
    tra_rad = if_else(mission == "AVI090806", NA_real_, tra_rad),
    dis_rad = if_else(mission == "AVI090806", NA_real_, dis_rad)
  )




# ── GOR140228 | UNKNOWN_CATALOG | transects$site [2026-03-27 08:44] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── GOR140228 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 08:44] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── GOR140228 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 08:44] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "GOR140228" &
      (heure < as.POSIXct("2014-02-28 00:00:00") |
       heure > as.POSIXct("2014-03-09 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── GOR140228 | UNKNOWN_CATALOG | observations$activite [2026-03-27 08:47] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── GOR140228 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 08:47] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "GOR140228" &
      (heure < as.POSIXct("2014-02-28 00:00:00") |
       heure > as.POSIXct("2014-03-09 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── GOR140228 | CV_R3 | observations$R3 [2026-03-27 08:53] ──
# R3 -- inspect rows with missing nb_individu or activite (mission GOR140228)
observations |> filter(mission == "GOR140228", id %in% c()) |>
  select(id, date, heure, code_espece, nb_individu, activite, snapshot, in_transect)

# Fix example — set nb_individu to 1 where missing (adjust as needed):
# observations <- observations |>
#   mutate(nb_individu = if_else(
#     mission == "GOR140228" & id %in% c() & is.na(nb_individu), 1L, nb_individu))


# ── GOR140228 | CV_R6 | observations$R6 [2026-03-27 08:56] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission GOR140228)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "GOR140228" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── GOR140228 | CV_R7 | observations$R7 [2026-03-27 08:58] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission GOR140228)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "GOR140228" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── HUD091025 | NUMERIC_OUTLIER_NA | transects$visibilite [2026-03-27 09:00] ──
# NA decision [visibilite]: Replace with median (20)
transects <- transects |>
  mutate(
    visibilite = if_else(mission == "HUD091025" & is.na(visibilite),
      20, visibilite)
  )

# ── HUD091025 | UNKNOWN_CATALOG | transects$site [2026-03-27 09:01] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── HUD091025 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 09:02] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── HUD091025 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 09:02] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "HUD091025" &
      (heure < as.POSIXct("2009-10-25 00:00:00") |
       heure > as.POSIXct("2009-11-13 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD091025 | UNKNOWN_CATALOG | observations$activite [2026-03-27 09:08] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── HUD091025 | UNKNOWN_CATALOG | observations$plumage [2026-03-27 09:09] ──
observations <- observations |>
  mutate(
    plumage = case_when(
      plumage == "Forme sombre" ~ "Forme Sombre",
      plumage == "Forme claire" ~ "Forme Claire",
      TRUE ~ plumage
    )
  )

# ── HUD091025 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 09:09] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "HUD091025" &
      (heure < as.POSIXct("2009-10-25 00:00:00") |
       heure > as.POSIXct("2009-11-13 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD091025 | CV_R4 | observations$R4 [2026-03-27 09:11] ──
# R4 fix: copy _rad into _par where _par is missing, then clear _rad
observations <- observations |>
  mutate(
    tra_par = if_else(mission == "HUD091025" &
      (is.na(tra_par) & is.na(dis_par)) & (!is.na(tra_rad) | !is.na(dis_rad)),
      tra_rad, tra_par),
    dis_par = if_else(mission == "HUD091025" &
      (is.na(tra_par) & is.na(dis_par)) & (!is.na(tra_rad) | !is.na(dis_rad)),
      dis_rad, dis_par),
    tra_rad = if_else(mission == "HUD091025" & !is.na(tra_par), NA_real_, tra_rad),
    dis_rad = if_else(mission == "HUD091025" & !is.na(dis_par), NA_real_, dis_rad)
  )

# ── HUD091025 | CV_R6 | observations$R6 [2026-03-27 09:13] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission HUD091025)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD091025" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── HUD091025 | CV_R9 | observations$R9 [2026-03-27 09:15] ──
# R9 -- inspect _rad vs _par discrepancies (mission HUD091025)
observations |> filter(mission == "HUD091025", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── HUD091025 | CV_R10 | transects$R10 [2026-03-27 09:16] ──
# R10 -- targeted inspection (mission HUD091025)
transects |> filter(mission == "HUD091025", id_transect %in% c(14158, 14164, 14182, 14190, 14194, 14197, 14207, 14221, 14236, 14300)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── HUD101107 | NUMERIC_OUTLIER_NA | transects$hau_yeux [2026-03-27 09:18] ──
# NA decision [hau_yeux]: Replace with median (999)
transects <- transects |>
  mutate(
    hau_yeux = if_else(mission == "HUD101107" & is.na(hau_yeux),
      999, hau_yeux)
  )

# ── HUD101107 | UNKNOWN_CATALOG | transects$site [2026-03-27 09:19] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── HUD101107 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 09:19] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── HUD101107 | UNKNOWN_CATALOG_NA | transects$act_plateforme [2026-03-27 09:20] ──
# NA decision [act_plateforme]: Custom value = Endéplacement
transects <- transects |>
  mutate(
    act_plateforme = if_else(mission == "HUD101107" & is.na(act_plateforme),
      "Endéplacement", act_plateforme)
  )

# ── HUD101107 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 09:21] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "HUD101107" &
      (heure < as.POSIXct("2010-11-07 00:00:00") |
       heure > as.POSIXct("2010-11-15 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD101107 | OUTSIDE_MISSION_DATES | transects$date_heure [2026-03-27 09:22] ──
transects <- transects |>
  mutate(
    date_heure = if_else(
      mission == "HUD101107" &
      (date_heure < as.POSIXct("2010-11-07 00:00:00") |
       date_heure > as.POSIXct("2010-11-15 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(date_heure, "%H:%M:%S")), tz="UTC"),
      date_heure
    )
  )

# ── HUD101107 | UNKNOWN_CATALOG | observations$activite [2026-03-27 09:24] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      activite == "Vol" ~ "VOL",
      TRUE ~ activite
    )
  )

# ── HUD101107 | UNKNOWN_CATALOG | observations$direction [2026-03-27 09:25] ──
observations <- observations |>
  mutate(
    direction = case_when(
      direction == "sw" ~ "E",
      direction == "sW" ~ "NW",
      direction == "w" ~ "E",
      direction == "Sw" ~ "S",
      direction == "s" ~ "E",
      TRUE ~ direction
    )
  )

# ── HUD101107 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 09:26] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "HUD101107" &
      (heure < as.POSIXct("2010-11-07 00:00:00") |
       heure > as.POSIXct("2010-11-15 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD101107 | OUTSIDE_MISSION_DATES | observations$date_heure [2026-03-27 09:28] ──
observations <- observations |>
  mutate(
    date_heure = if_else(
      mission == "HUD101107" &
      (date_heure < as.POSIXct("2010-11-07 00:00:00") |
       date_heure > as.POSIXct("2010-11-15 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(date_heure, "%H:%M:%S")), tz="UTC"),
      date_heure
    )
  )

# ── HUD101107 | CV_R6 | observations$R6 [2026-03-27 09:29] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission HUD101107)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD101107" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── HUD101107 | CV_R9 | observations$R9 [2026-03-27 09:30] ──
# R9 -- inspect _rad vs _par discrepancies (mission HUD101107)
observations |> filter(mission == "HUD101107", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── HUD101107 | CV_R10 | transects$R10 [2026-03-27 09:32] ──
# R10 -- targeted inspection (mission HUD101107)
transects |> filter(mission == "HUD101107", id_transect %in% c(20017, 20048, 20127, 20160, 20184)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)

# R10 -- impute missing vit_plateforme from computed speed (knots)
vit_impute <- run_cross_validation("HUD101107")$R10 |>
  dplyr::filter(reason == "vit_plateforme_manquante") |>
  dplyr::transmute(id_transect, vit_calc_kn = Observed_kmh / 1.852)

transects <- transects |>
  dplyr::left_join(vit_impute, by = "id_transect") |>
  dplyr::mutate(vit_plateforme = dplyr::if_else(
    mission == "HUD101107" & id_transect %in% c(20017, 20048) & is.na(vit_plateforme),
    vit_calc_kn, vit_plateforme
  )) |>
  dplyr::select(-vit_calc_kn)


# ── HUD111102 | NUMERIC_OUTLIER_NA | transects$visibilite [2026-03-27 09:37] ──
# NA decision [visibilite]: Replace with median (20)
transects <- transects |>
  mutate(
    visibilite = if_else(mission == "HUD111102" & is.na(visibilite),
      20, visibilite)
  )

# ── HUD111102 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-27 09:39] ──
# NA decision [vagues]: Replace with median (0.5)
#transects <- transects |>
#  mutate(
#    vagues = if_else(mission == "HUD111102" & is.na(vagues),
#      0.5, vagues) #devrait plutot changera la valeur précédente
#  )

# ── HUD111102 | UNKNOWN_CATALOG | transects$site [2026-03-27 09:43] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── HUD111102 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 09:43] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── HUD111102 | UNKNOWN_CATALOG_NA | transects$act_plateforme [2026-03-27 09:44] ──
# NA decision [act_plateforme]: Custom value = Endéplacement
transects <- transects |>
  mutate(
    act_plateforme = if_else(mission == "HUD111102" & is.na(act_plateforme),
      "Endéplacement", act_plateforme)
  )

# ── HUD111102 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 09:44] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "HUD111102" &
      (heure < as.POSIXct("2011-11-02 00:00:00") |
       heure > as.POSIXct("2011-11-11 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD111102 | UNKNOWN_CATALOG | observations$activite [2026-03-27 09:45] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── HUD111102 | UNKNOWN_CATALOG | observations$snapshot [2026-03-27 09:46] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── HUD111102 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 09:46] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "HUD111102" &
      (heure < as.POSIXct("2011-11-02 00:00:00") |
       heure > as.POSIXct("2011-11-11 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD111102 | CV_R4 | observations$R4 [2026-03-27 09:49] ──
# R4 -- inspect rows with missing distance data (mission HUD111102)
observations |> filter(mission == "HUD111102", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── HUD111102 | CV_R6 | observations$R6 [2026-03-27 09:49] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission HUD111102)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD111102" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── HUD111102 | CV_R7 | observations$R7 [2026-03-27 09:50] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission HUD111102)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD111102" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── HUD111102 | CV_R10 | transects$R10 [2026-03-27 09:51] ──
# R10 -- targeted inspection (mission HUD111102)
transects |> filter(mission == "HUD111102", id_transect %in% c(2, 32, 36, 37, 38, 40, 41)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── HUD121030 | DIRECTION_RANGE_OUTLIER | transects$dir_vent [2026-03-27 09:53] ──
transects <- transects |>
  mutate(
    dir_vent = dir_vent  # reviewer decision, valeur = 395 à changer pour ??
  )

# ── HUD121030 | UNKNOWN_CATALOG | transects$site [2026-03-27 09:54] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── HUD121030 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 09:55] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── HUD121030 | UNKNOWN_CATALOG | transects$int_exterieur [2026-03-27 09:55] ──
transects <- transects |>
  mutate(
    int_exterieur = case_when(
      int_exterieur == "Intérieur" ~ "Interieur",
      TRUE ~ int_exterieur
    )
  )

# ── HUD121030 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 09:55] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "HUD121030" &
      (heure < as.POSIXct("2012-10-30 00:00:00") |
       heure > as.POSIXct("2012-11-10 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD121030 | UNKNOWN_CATALOG | observations$activite [2026-03-27 09:56] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      activite == "Vol" ~ "VOL",
      TRUE ~ activite
    )
  )

# ── HUD121030 | UNKNOWN_CATALOG | observations$sexe [2026-03-27 09:58] ──
observations <- observations |>
  mutate(
    sexe = case_when(
      sexe == "Femelle" ~ "F",
      sexe == "Male" ~ "M",
      TRUE ~ sexe
    )
  )

# ── HUD121030 | UNKNOWN_CATALOG | observations$snapshot [2026-03-27 09:58] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "non" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── HUD121030 | UNKNOWN_CATALOG | observations$cote_obs [2026-03-27 09:58] ──
observations <- observations |>
  mutate(
    cote_obs = case_when(
      cote_obs == "BABORD" ~ "Babord",
      TRUE ~ cote_obs
    )
  )

# ── HUD121030 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:00] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "HUD121030" &
      (heure < as.POSIXct("2012-10-30 00:00:00") |
       heure > as.POSIXct("2012-11-10 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD121030 | OUTSIDE_MISSION_DATES | observations$date_heure [2026-03-27 10:00] ──
observations <- observations |>
  mutate(
    date_heure = if_else(
      mission == "HUD121030" &
      (date_heure < as.POSIXct("2012-10-30 00:00:00") |
       date_heure > as.POSIXct("2012-11-10 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(date_heure, "%H:%M:%S")), tz="UTC"),
      date_heure
    )
  )

# ── HUD121030 | CV_R1 | observations$R1 [2026-03-27 10:01] ──
# R1 -- assign missing id_transect (mission HUD121030)
# Inspect these observation ids and assign manually:
observations |> filter(mission == "HUD121030", id %in% c()) |>
  select(id, date, heure, in_transect, id_transect, code_espece)

# Example fix (replace XX with correct transect id):
# observations <- observations |>
#   mutate(id_transect = if_else(mission == "HUD121030" & id %in% c(), XX, id_transect))


# ── HUD121030 | CV_R6 | observations$R6 [2026-03-27 10:04] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission HUD121030)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD121030" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── HUD121030 | CV_R7 | observations$R7 [2026-03-27 10:04] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission HUD121030)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD121030" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── HUD121030 | CV_R10 | transects$R10 [2026-03-27 10:05] ──
# R10 -- targeted inspection (mission HUD121030)
transects |> filter(mission == "HUD121030", id_transect %in% c(7, 43)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── HUD121106 | UNKNOWN_CATALOG | transects$site [2026-03-27 10:08] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── HUD121106 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 10:08] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── HUD121106 | UNKNOWN_CATALOG_NA | transects$act_plateforme [2026-03-27 10:09] ──
# NA decision [act_plateforme]: Custom value = Endéplacement
transects <- transects |>
  mutate(
    act_plateforme = if_else(mission == "HUD121106" & is.na(act_plateforme),
      "Endéplacement", act_plateforme)
  )

# ── HUD121106 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:09] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "HUD121106" &
      (heure < as.POSIXct("2012-11-06 00:00:00") |
       heure > as.POSIXct("2012-11-06 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD121106 | UNKNOWN_CATALOG | observations$activite [2026-03-27 10:10] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      activite == "Vol" ~ "VOL",
      TRUE ~ activite
    )
  )

# ── HUD121106 | UNKNOWN_CATALOG | observations$snapshot [2026-03-27 10:10] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── HUD121106 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:10] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "HUD121106" &
      (heure < as.POSIXct("2012-11-06 00:00:00") |
       heure > as.POSIXct("2012-11-06 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD121106 | CV_R4 | observations$R4 [2026-03-27 10:11] ──
# R4 -- inspect rows with missing distance data (mission HUD121106)
observations |> filter(mission == "HUD121106", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── HUD121106 | CV_R6 | observations$R6 [2026-03-27 10:11] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission HUD121106)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD121106" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── HUD121106 | CV_R10 | transects$R10 [2026-03-27 10:12] ──
# R10 -- targeted inspection (mission HUD121106)
transects |> filter(mission == "HUD121106", id_transect %in% c(22906, 22916)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── HUD131029 | NUMERIC_OUTLIER_NA | transects$visibilite [2026-03-27 10:13] ──
# NA decision [visibilite]: Replace with median (20)
transects <- transects |>
  mutate(
    visibilite = if_else(mission == "HUD131029" & is.na(visibilite),
      20, visibilite)
  )

# ── HUD131029 | NUMERIC_OUTLIER_NA | transects$vit_vent [2026-03-27 10:14] ──
# NA decision [vit_vent]: Custom value = 5.6
transects <- transects |>
  mutate(
    vit_vent = if_else(mission == "HUD131029" & is.na(vit_vent),
      5.6, vit_vent)
  )

# ── HUD131029 | UNKNOWN_CATALOG | transects$site [2026-03-27 10:16] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Mitoyen" ~ "mitoyen",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── HUD131029 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 10:16] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── HUD131029 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:16] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "HUD131029" &
      (heure < as.POSIXct("2013-10-29 00:00:00") |
       heure > as.POSIXct("2013-11-11 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD131029 | UNKNOWN_CATALOG | observations$activite [2026-03-27 10:18] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── HUD131029 | UNKNOWN_CATALOG | observations$age [2026-03-27 10:19] ──
observations <- observations |>
  mutate(
    age = case_when(
      age == "Adulte " ~ "Adulte",
      TRUE ~ age
    )
  )

# ── HUD131029 | UNKNOWN_CATALOG | observations$in_transect [2026-03-27 10:19] ──
observations <- observations |>
  mutate(
    in_transect = case_when(
      in_transect == "Hors Transect" ~ "Hors transect",
      TRUE ~ in_transect
    )
  )

# ── HUD131029 | UNKNOWN_CATALOG | observations$snapshot [2026-03-27 10:19] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── HUD131029 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:19] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "HUD131029" &
      (heure < as.POSIXct("2013-10-29 00:00:00") |
       heure > as.POSIXct("2013-11-11 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── HUD131029 | CV_R5 | observations$R5 [2026-03-27 10:21] ──
# R5 fix: copy _rad -> _par where _par is missing, then clear _rad (mission HUD131029)
observations <- observations |>
  mutate(
    tra_par = if_else(
      mission == "HUD131029" & is.na(tra_par) & !is.na(tra_rad),
      tra_rad, tra_par),
    dis_par = if_else(
      mission == "HUD131029" & is.na(dis_par) & !is.na(dis_rad),
      dis_rad, dis_par),
    tra_rad = if_else(mission == "HUD131029", NA_real_, tra_rad),
    dis_rad = if_else(mission == "HUD131029", NA_real_, dis_rad)
  )


# ── HUD131029 | CV_R6 | observations$R6 [2026-03-27 10:22] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission HUD131029)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD131029" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── HUD131029 | CV_R7 | observations$R7 [2026-03-27 10:22] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission HUD131029)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "HUD131029" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── HUD131029 | CV_R10 | transects$R10 [2026-03-27 10:22] ──
# R10 -- targeted inspection (mission HUD131029)
transects |> filter(mission == "HUD131029", id_transect %in% c(25117, 25179, 25185)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── ISL130421 | UNKNOWN_CATALOG | transects$site [2026-03-27 10:24] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Mitoyen" ~ "mitoyen",
      site == "Fin" ~ "fin",
      site == "Description initiale" ~ "description initiale",
      TRUE ~ site
    )
  )

# ── ISL130421 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:24] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "ISL130421" &
      (heure < as.POSIXct("2013-04-21 00:00:00") |
       heure > as.POSIXct("2013-04-23 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── ISL130421 | UNKNOWN_CATALOG | observations$activite [2026-03-27 10:26] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── ISL130421 | UNKNOWN_CATALOG | observations$code_obs [2026-03-27 10:27] ──
observations <- observations |>
  mutate(
    code_obs = case_when(
      code_obs == "JG" ~ "CG",
      code_obs == "FB" ~ "FB",
      code_obs == "PB" ~ "PB",
      TRUE ~ code_obs
    )
  )

# ── ISL130421 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:27] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "ISL130421" &
      (heure < as.POSIXct("2013-04-21 00:00:00") |
       heure > as.POSIXct("2013-04-23 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── MLB090423 | NUMERIC_OUTLIER_NA | transects$vit_plateforme [2026-03-27 10:29] ──
# NA decision [vit_plateforme]: Replace with mean (13.7939)
transects <- transects |>
  mutate(
    vit_plateforme = if_else(mission == "MLB090423" & is.na(vit_plateforme),
      13.7939, vit_plateforme)
  )

# ── MLB090423 | NUMERIC_OUTLIER_NA | transects$visibilite [2026-03-27 10:30] ──
# NA decision [visibilite]: Replace with median (20)
transects <- transects |>
  mutate(
    visibilite = if_else(mission == "MLB090423" & is.na(visibilite),
      20, visibilite)
  )

# ── MLB090423 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-27 10:31] ──
# NA decision [vagues]: Custom value = 1
transects <- transects |>
  mutate(
    vagues = if_else(mission == "MLB090423" & is.na(vagues),
      1, vagues)
  )

# ── MLB090423 | NUMERIC_OUTLIER_NA | transects$vit_vent [2026-03-27 10:32] ──
# NA decision [vit_vent]: Custom value = 12
transects <- transects |>
  mutate(
    vit_vent = if_else(mission == "MLB090423" & is.na(vit_vent),
      12, vit_vent)
  )

# ── MLB090423 | UNKNOWN_CATALOG | transects$site [2026-03-27 10:34] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      site == "Début initiale" ~ "début",
      site == "Mitoyen" ~ "mitoyen",
      TRUE ~ site
    )
  )

# ── MLB090423 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 10:34] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── MLB090423 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:34] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "MLB090423" &
      (heure < as.POSIXct("2009-04-23 00:00:00") |
       heure > as.POSIXct("2009-05-14 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── MLB090423 | UNKNOWN_CATALOG | observations$activite [2026-03-27 10:35] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── MLB090423 | UNKNOWN_CATALOG | observations$in_transect [2026-03-27 10:36] ──
observations <- observations |>
  mutate(
    in_transect = case_when(
      in_transect == "hors transect" ~ "Hors transect",
      TRUE ~ in_transect
    )
  )

# ── MLB090423 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:36] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "MLB090423" &
      (heure < as.POSIXct("2009-04-23 00:00:00") |
       heure > as.POSIXct("2009-05-14 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── MLB090423 | CV_R6 | observations$R6 [2026-03-27 10:38] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission MLB090423)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "MLB090423" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── MLB090423 | CV_R10 | transects$R10 [2026-03-27 10:39] ──
# R10 -- targeted inspection (mission MLB090423)
transects |> filter(mission == "MLB090423", id_transect %in% c(10259)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── MLB090423 | CV_R11 | transects$R11 [2026-03-27 10:40] ──
# R11 -- inspect transects with endpoint issues (mission MLB090423)
transects |> filter(mission == "MLB090423", id_transect %in% c(10259)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme) |>
  arrange(id_transect, date_heure)

# R11 -- auto-create missing Debut/Fin rows for transects with exactly one missing endpoint
norm_site <- function(x) {
  y <- tolower(iconv(as.character(x), to = "ASCII//TRANSLIT"))
  dplyr::case_when(
    y %in% c("debut", "start") ~ "debut",
    y %in% c("fin", "end") ~ "fin",
    TRUE ~ NA_character_
  )
}

t_mis <- transects |>
  dplyr::filter(mission == "MLB090423") |>
  dplyr::mutate(site_norm = norm_site(site), dt = suppressWarnings(lubridate::as_datetime(date_heure)))

status <- t_mis |>
  dplyr::group_by(id_transect) |>
  dplyr::summarise(
    n_debut = sum(site_norm == "debut", na.rm = TRUE),
    n_fin = sum(site_norm == "fin", na.rm = TRUE),
    issue = dplyr::case_when(
      n_debut == 0 & n_fin > 0 ~ "missing_debut",
      n_fin == 0 & n_debut > 0 ~ "missing_fin",
      TRUE ~ "other"
    ),
    .groups = "drop"
  ) |>
  dplyr::filter(issue %in% c("missing_debut", "missing_fin"), id_transect %in% c(10259))

first_rows <- t_mis |>
  dplyr::arrange(id_transect, is.na(dt), dt) |>
  dplyr::group_by(id_transect) |>
  dplyr::slice_head(n = 1) |>
  dplyr::ungroup()

last_rows <- t_mis |>
  dplyr::arrange(id_transect, is.na(dt), dplyr::desc(dt)) |>
  dplyr::group_by(id_transect) |>
  dplyr::slice_head(n = 1) |>
  dplyr::ungroup()

rows_debut <- status |>
  dplyr::filter(issue == "missing_debut") |>
  dplyr::inner_join(first_rows, by = "id_transect") |>
  dplyr::mutate(site = "Début")

rows_fin <- status |>
  dplyr::filter(issue == "missing_fin") |>
  dplyr::inner_join(last_rows, by = "id_transect") |>
  dplyr::mutate(site = "Fin")

rows_to_add <- dplyr::bind_rows(rows_debut, rows_fin) |>
  dplyr::select(-n_debut, -n_fin, -issue, -site_norm, -dt)

transects <- dplyr::bind_rows(transects, rows_to_add)


# ── PAR110727 | NUMERIC_OUTLIER_OUTLIER | transects$dir_vent [2026-03-27 10:42] ──
transects <- transects |>
  mutate(
    dir_vent = dir_vent  # reviewer decision
  )

# ── PAR110727 | UNKNOWN_CATALOG | transects$site [2026-03-27 10:42] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Mitoyen" ~ "mitoyen",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── PAR110727 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:43] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "PAR110727" &
      (heure < as.POSIXct("2011-07-27 00:00:00") |
       heure > as.POSIXct("2011-07-29 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR110727 | UNKNOWN_CATALOG | observations$activite [2026-03-27 10:43] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── PAR110727 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:43] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "PAR110727" &
      (heure < as.POSIXct("2011-07-27 00:00:00") |
       heure > as.POSIXct("2011-07-29 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR110727 | CV_R4 | observations$R4 [2026-03-27 10:45] ──
# R4 -- inspect rows with missing distance data (mission PAR110727)
observations |> filter(mission == "PAR110727", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── PAR111214 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-27 10:47] ──
# NA decision [vagues]: Custom value = 0.5
transects <- transects |>
  mutate(
    vagues = if_else(mission == "PAR111214" & is.na(vagues),
      0.5, vagues)
  )

# ── PAR111214 | UNKNOWN_CATALOG | transects$site [2026-03-27 10:47] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Mitoyen" ~ "mitoyen",
      site == "Fin" ~ "fin",
      site == "Description initiale" ~ "description initiale",
      TRUE ~ site
    )
  )

# ── PAR111214 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:48] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "PAR111214" &
      (heure < as.POSIXct("2011-12-14 00:00:00") |
       heure > as.POSIXct("2011-12-18 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR111214 | UNKNOWN_CATALOG | observations$activite [2026-03-27 10:48] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      activite == "Vol" ~ "VOL",
      TRUE ~ activite
    )
  )

# ── PAR111214 | UNKNOWN_CATALOG_NA | observations$activite [2026-03-27 10:49] ──
# NA decision [activite]: Custom value = VOL
observations <- observations |>
  mutate(
    activite = if_else(mission == "PAR111214" & is.na(activite),
      "VOL", activite)
  )

# ── PAR111214 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:49] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "PAR111214" &
      (heure < as.POSIXct("2011-12-14 00:00:00") |
       heure > as.POSIXct("2011-12-18 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR111214 | CV_R3 | observations$R3 [2026-03-27 10:50] ──
# R3 -- inspect rows with missing nb_individu or activite (mission PAR111214)
observations |> filter(mission == "PAR111214", id %in% c()) |>
  select(id, date, heure, code_espece, nb_individu, activite, snapshot, in_transect)

# Fix example — set nb_individu to 1 where missing (adjust as needed):
# observations <- observations |>
#   mutate(nb_individu = if_else(
#     mission == "PAR111214" & id %in% c() & is.na(nb_individu), 1L, nb_individu))


# ── PAR111214 | CV_R4 | observations$R4 [2026-03-27 10:51] ──
# R4 -- inspect rows with missing distance data (mission PAR111214)
observations |> filter(mission == "PAR111214", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── PAR120312 | NUMERIC_OUTLIER_NA | transects$dir_vent [2026-03-27 10:53] ──
# NA decision [dir_vent]: Custom value = 90
transects <- transects |>
  mutate(
    dir_vent = if_else(mission == "PAR120312" & is.na(dir_vent),
      90, dir_vent)
  )

# ── PAR120312 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:53] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "PAR120312" &
      (heure < as.POSIXct("2012-03-12 00:00:00") |
       heure > as.POSIXct("2012-03-15 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR120312 | UNKNOWN_CATALOG | observations$activite [2026-03-27 10:54] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── PAR120312 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 10:55] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "PAR120312" &
      (heure < as.POSIXct("2012-03-12 00:00:00") |
       heure > as.POSIXct("2012-03-15 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR120312 | CV_R4 | observations$R4 [2026-03-27 10:56] ──
# R4 -- inspect rows with missing distance data (mission PAR120312)
observations |> filter(mission == "PAR120312", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── PAR120321 | UNKNOWN_CATALOG | transects$site [2026-03-27 10:57] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Mitoyen" ~ "mitoyen",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── PAR120321 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 10:57] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "PAR120321" &
      (heure < as.POSIXct("2012-03-21 00:00:00") |
       heure > as.POSIXct("2012-03-22 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR120321 | NUMERIC_OUTLIER_NA | observations$nb_individu [2026-03-27 10:58] ──
# NA decision [nb_individu]: Replace with median (1)
observations <- observations |>
  mutate(
    nb_individu = if_else(mission == "PAR120321" & is.na(nb_individu),
      1, nb_individu)
  )

# ── PAR120321 | NUMERIC_OUTLIER_OUTLIER | observations$longitude [2026-03-27 10:59] ──
observations <- observations |>
  mutate(
    longitude = longitude  # reviewer decision
  )

# ── PAR120321 | UNKNOWN_CATALOG | observations$activite [2026-03-27 11:00] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── PAR120321 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 11:01] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "PAR120321" &
      (heure < as.POSIXct("2012-03-21 00:00:00") |
       heure > as.POSIXct("2012-03-22 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR130430 | UNKNOWN_CATALOG | transects$site [2026-03-27 11:04] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Description initiale" ~ "description initiale",
      site == "Début" ~ "début",
      site == "Mitoyen" ~ "mitoyen",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── PAR130430 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 11:04] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "PAR130430" &
      (heure < as.POSIXct("2013-04-30 00:00:00") |
       heure > as.POSIXct("2013-05-01 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PAR130430 | UNKNOWN_CATALOG | observations$activite [2026-03-27 11:06] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── PAR130430 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 11:06] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "PAR130430" &
      (heure < as.POSIXct("2013-04-30 00:00:00") |
       heure > as.POSIXct("2013-05-01 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PER130717 | NUMERIC_OUTLIER_NA | transects$vit_plateforme [2026-03-27 11:08] ──
# NA decision [vit_plateforme]: Replace with median (9.5)
transects <- transects |>
  mutate(
    vit_plateforme = if_else(mission == "PER130717" & is.na(vit_plateforme),
      9.5, vit_plateforme)
  )

# ── PER130717 | NUMERIC_OUTLIER_NA | transects$visibilite [2026-03-27 11:08] ──
# NA decision [visibilite]: Replace with median (20)
transects <- transects |>
  mutate(
    visibilite = if_else(mission == "PER130717" & is.na(visibilite),
      20, visibilite)
  )

# ── PER130717 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-27 11:09] ──
# NA decision [vagues]: Replace with median (0.5)
transects <- transects |>
  mutate(
    vagues = if_else(mission == "PER130717" & is.na(vagues),
      0.5, vagues)
  )

# ── PER130717 | UNKNOWN_CATALOG | transects$site [2026-03-27 11:12] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── PER130717 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 11:12] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── PER130717 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 11:12] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "PER130717" &
      (heure < as.POSIXct("2013-07-17 00:00:00") |
       heure > as.POSIXct("2013-08-14 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PER130717 | UNKNOWN_CATALOG | observations$code_espece [2026-03-27 11:13] ──
observations <- observations |>
  mutate(
    code_espece = case_when(
      code_espece == "COAi" ~ "COAI",
      code_espece == "goar" ~ "ALHC",
      TRUE ~ code_espece
    )
  )

# ── PER130717 | UNKNOWN_CATALOG | observations$activite [2026-03-27 11:14] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── PER130717 | UNKNOWN_CATALOG | observations$in_transect [2026-03-27 11:14] ──
observations <- observations |>
  mutate(
    in_transect = case_when(
      in_transect == "Hors Transect" ~ "Hors transect",
      TRUE ~ in_transect
    )
  )

# ── PER130717 | UNKNOWN_CATALOG | observations$snapshot [2026-03-27 11:14] ──
observations <- observations |>
  mutate(
    snapshot = case_when(
      snapshot == "NON" ~ "Non",
      TRUE ~ snapshot
    )
  )

# ── PER130717 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 11:15] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "PER130717" &
      (heure < as.POSIXct("2013-07-17 00:00:00") |
       heure > as.POSIXct("2013-08-14 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── PER130717 | CV_R3 | observations$R3 [2026-03-27 11:16] ──
# R3 -- inspect rows with missing nb_individu or activite (mission PER130717)
observations |> filter(mission == "PER130717", id %in% c()) |>
  select(id, date, heure, code_espece, nb_individu, activite, snapshot, in_transect)

# Fix example — set nb_individu to 1 where missing (adjust as needed):
# observations <- observations |>
#   mutate(nb_individu = if_else(
#     mission == "PER130717" & id %in% c() & is.na(nb_individu), 1L, nb_individu))


# ── PER130717 | CV_R4 | observations$R4 [2026-03-27 11:17] ──
# R4 fix: copy _rad into _par where _par is missing, then clear _rad
observations <- observations |>
  mutate(
    tra_par = if_else(mission == "PER130717" &
      (is.na(tra_par) & is.na(dis_par)) & (!is.na(tra_rad) | !is.na(dis_rad)),
      tra_rad, tra_par),
    dis_par = if_else(mission == "PER130717" &
      (is.na(tra_par) & is.na(dis_par)) & (!is.na(tra_rad) | !is.na(dis_rad)),
      dis_rad, dis_par),
    tra_rad = if_else(mission == "PER130717" & !is.na(tra_par), NA_real_, tra_rad),
    dis_rad = if_else(mission == "PER130717" & !is.na(dis_par), NA_real_, dis_rad)
  )

# ── PER130717 | CV_R6 | observations$R6 [2026-03-27 11:17] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission PER130717)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "PER130717" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── PER130717 | CV_R7 | observations$R7 [2026-03-27 11:18] ──
# R7 fix: set snapshot = 'Non' where activite = EAU (mission PER130717)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "PER130717" &
      str_to_upper(str_trim(activite)) == "EAU" &
      str_to_upper(str_trim(snapshot)) != "NON",
      "Non", snapshot
    )
  )

# ── PER130717 | CV_R10 | transects$R10 [2026-03-27 11:18] ──
# R10 -- targeted inspection (mission PER130717)
transects |> filter(mission == "PER130717", id_transect %in% c(23521, 23540, 23624, 23715, 23772, 23795, 23917, 23993, 24099)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── TEL100603 | UNKNOWN_CATALOG | transects$site [2026-03-27 11:20] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── TEL100603 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 11:21] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL100603" &
      (heure < as.POSIXct("2010-06-03 00:00:00") |
       heure > as.POSIXct("2010-06-19 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL100603 | UNKNOWN_CATALOG | observations$activite [2026-03-27 11:22] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  )

# ── TEL100603 | UNKNOWN_CATALOG | observations$plumage [2026-03-27 11:23] ──
observations <- observations |>
  mutate(
    plumage = case_when(
      plumage == "Forme claire" ~ "Forme Claire",
      plumage == "Forme sombre" ~ "Forme Sombre",
      TRUE ~ plumage
    )
  )

# ── TEL100603 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 11:23] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL100603" &
      (heure < as.POSIXct("2010-06-03 00:00:00") |
       heure > as.POSIXct("2010-06-19 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL100603 | CV_R6 | observations$R6 [2026-03-27 11:24] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL100603)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL100603" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL100603 | CV_R9 | observations$R9 [2026-03-27 11:24] ──
# R9 -- inspect _rad vs _par discrepancies (mission TEL100603)
observations |> filter(mission == "TEL100603", id %in% c()) |>
  select(id, date, heure, code_espece, activite, tra_rad, dis_rad, tra_par, dis_par)


# ── TEL100603 | CV_R10 | transects$R10 [2026-03-27 11:25] ──
# R10 -- targeted inspection (mission TEL100603)
transects |> filter(mission == "TEL100603", id_transect %in% c(7, 8, 37, 42, 43, 64, 68, 77, 78)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)


# ── TEL110817 | NUMERIC_OUTLIER_NA | transects$vit_plateforme [2026-03-27 11:27] ──
# NA decision [vit_plateforme]: Replace with median (10.65)
transects <- transects |>
  mutate(
    vit_plateforme = if_else(mission == "TEL110817" & is.na(vit_plateforme),
      10.65, vit_plateforme)
  )

# ── TEL110817 | NUMERIC_OUTLIER_NA | transects$visibilite [2026-03-27 11:27] ──
# NA decision [visibilite]: Replace with median (20)
transects <- transects |>
  mutate(
    visibilite = if_else(mission == "TEL110817" & is.na(visibilite),
      20, visibilite)
  )

# ── TEL110817 | NUMERIC_OUTLIER_NA | transects$vagues [2026-03-27 11:28] ──
# NA decision [vagues]: Replace with median (0.25)
transects <- transects |>
  mutate(
    vagues = if_else(mission == "TEL110817" & is.na(vagues),
      0.25, vagues)
  )

# ── TEL110817 | UNKNOWN_CATALOG | transects$site [2026-03-27 11:28] ──
transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  )

# ── TEL110817 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-27 11:28] ──
transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  )

# ── TEL110817 | UNKNOWN_CATALOG_NA | transects$act_plateforme [2026-03-27 11:29] ──
# NA decision [act_plateforme]: Custom value = Endéplacement
transects <- transects |>
  mutate(
    act_plateforme = if_else(mission == "TEL110817" & is.na(act_plateforme),
      "Endéplacement", act_plateforme)
  )

# ── TEL110817 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-27 11:29] ──
transects <- transects |>
  mutate(
    heure = if_else(
      mission == "TEL110817" &
      (heure < as.POSIXct("2011-08-17 00:00:00") |
       heure > as.POSIXct("2011-08-28 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL110817 | UNKNOWN_CATALOG | observations$code_espece [2026-03-27 11:30] ──
observations <- observations |>
  mutate(
    code_espece = case_when(
      code_espece == "rien" ~ "ALHC",
      code_espece == "plhu" ~ "ALHC",
      code_espece == "goma" ~ "ALHC",
      code_espece == "pepi" ~ "ALHC",
      code_espece == "motr" ~ "ALHC",
      code_espece == "lasp" ~ "ALHC",
      code_espece == "fubo" ~ "ALHC",
      code_espece == "goar" ~ "ALHC",
      code_espece == "puma" ~ "ALHC",
      code_espece == "guma" ~ "ALHC",
      code_espece == "gumi" ~ "ALHC",
      code_espece == "occb" ~ "ALHC",
      code_espece == "gosp" ~ "ALHC",
      code_espece == "ocsp" ~ "ALHC",
      code_espece == "alsp" ~ "ALHC",
      code_espece == "lapo" ~ "ALHC",
      code_espece == "lapa" ~ "ALHC",
      code_espece == "phbe" ~ "ALHC",
      code_espece == "caSP" ~ "ALSP",
      code_espece == "mamo" ~ "ALHC",
      code_espece == "coai" ~ "ALHC",
      code_espece == "gobc" ~ "ALHC",
      code_espece == "phsp" ~ "ALHC",
      code_espece == "plca" ~ "ALHC",
      code_espece == "plsp" ~ "ALHC",
      code_espece == "mena" ~ "ALHC",
      code_espece == "OCcb" ~ "OCCB",
      code_espece == "oisp" ~ "ALHC",
      code_espece == "pusp" ~ "ALHC",
      TRUE ~ code_espece
    )
  )

# ── TEL110817 | UNKNOWN_CATALOG | observations$activite [2026-03-27 11:30] ──
observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Eau" ~ "EAU",
      activite == "Navire" ~ "NAVIRE",
      TRUE ~ activite
    )
  )

# ── TEL110817 | UNKNOWN_CATALOG | observations$tra_par [2026-03-27 11:31] ──
observations <- observations |>
  mutate(
    tra_par = case_when(
      tra_par == "exterieur" ~ "Exterieur",
      TRUE ~ tra_par
    )
  )

# ── TEL110817 | UNKNOWN_CATALOG | observations$plumage [2026-03-27 11:31] ──
observations <- observations |>
  mutate(
    plumage = case_when(
      plumage == "Forme claire" ~ "Forme Claire",
      TRUE ~ plumage
    )
  )

# ── TEL110817 | OUTSIDE_MISSION_DATES | observations$heure [2026-03-27 11:31] ──
observations <- observations |>
  mutate(
    heure = if_else(
      mission == "TEL110817" &
      (heure < as.POSIXct("2011-08-17 00:00:00") |
       heure > as.POSIXct("2011-08-28 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  )

# ── TEL110817 | CV_R1 | observations$R1 [2026-03-27 11:32] ──
# R1 -- assign missing id_transect (mission TEL110817)
# Inspect these observation ids and assign manually:
observations |> filter(mission == "TEL110817", id %in% c()) |>
  select(id, date, heure, in_transect, id_transect, code_espece)

# Example fix (replace XX with correct transect id):
# observations <- observations |>
#   mutate(id_transect = if_else(mission == "TEL110817" & id %in% c(), XX, id_transect))


# ── TEL110817 | CV_R4 | observations$R4 [2026-03-27 11:33] ──
# R4 fix: copy _rad into _par where _par is missing, then clear _rad
observations <- observations |>
  mutate(
    tra_par = if_else(mission == "TEL110817" &
      (is.na(tra_par) & is.na(dis_par)) & (!is.na(tra_rad) | !is.na(dis_rad)),
      tra_rad, tra_par),
    dis_par = if_else(mission == "TEL110817" &
      (is.na(tra_par) & is.na(dis_par)) & (!is.na(tra_rad) | !is.na(dis_rad)),
      dis_rad, dis_par),
    tra_rad = if_else(mission == "TEL110817" & !is.na(tra_par), NA_real_, tra_rad),
    dis_rad = if_else(mission == "TEL110817" & !is.na(dis_par), NA_real_, dis_rad)
  )

# ── TEL110817 | CV_R6 | observations$R6 [2026-03-27 11:34] ──
# R6 fix: set snapshot = 'Oui' where activite = VOL (mission TEL110817)
observations <- observations |>
  mutate(
    snapshot = if_else(
      mission == "TEL110817" &
      str_to_upper(str_trim(activite)) == "VOL" &
      str_to_upper(str_trim(snapshot)) != "OUI",
      "Oui", snapshot
    )
  )

# ── TEL110817 | CV_R10 | transects$R10 [2026-03-27 11:34] ──
# R10 -- targeted inspection (mission TEL110817)
transects |> filter(mission == "TEL110817", id_transect %in% c(3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 18, 19, 20, 23, 26, 30, 31, 33, 34, 38)) |>
  select(mission, id_transect, site, date_heure, longitude, latitude, vit_plateforme)

# R10 -- impute missing vit_plateforme from computed speed (knots)
vit_impute <- run_cross_validation("TEL110817")$R10 |>
  dplyr::filter(reason == "vit_plateforme_manquante") |>
  dplyr::transmute(id_transect, vit_calc_kn = Observed_kmh / 1.852)

transects <- transects |>
  dplyr::left_join(vit_impute, by = "id_transect") |>
  dplyr::mutate(vit_plateforme = dplyr::if_else(
    mission == "TEL110817" & id_transect %in% c(4, 5, 7, 8, 9, 10, 11, 15, 18, 19, 23, 26, 30, 31, 34, 38) & is.na(vit_plateforme),
    vit_calc_kn, vit_plateforme
  )) |>
  dplyr::select(-vit_calc_kn)



# ============================================================
# CLOSING — save updated RDS + create new accdb (Windows only)
# ============================================================

saveRDS(missions,     file.path(.cache_dir, "missions.rds"))
saveRDS(transects,    file.path(.cache_dir, "transects.rds"))
saveRDS(observations, file.path(.cache_dir, "observations.rds"))
cat("\u2705 Updated RDS files saved.\n")

if (.Platform$OS.type == "windows") {
  .gestion_root <- dirname(.repo_root)
  .somec_root   <- dirname(.gestion_root)
  .accdb_src    <- file.path(.somec_root, "BaseDeDonnees", "SOMEC_20251106.accdb")
  .accdb_dst    <- file.path(.somec_root, "BaseDeDonnees", "SOMEC_20260327.accdb")
  file.copy(.accdb_src, .accdb_dst, overwrite = FALSE)
  con <- RODBC::odbcConnectAccess2007(.accdb_dst, believeNRows = FALSE)
  RODBC::sqlSave(con, missions,     tablename = "missions",     rownames = FALSE, append = FALSE)
  RODBC::sqlSave(con, transects,    tablename = "transects",    rownames = FALSE, append = FALSE)
  RODBC::sqlSave(con, observations, tablename = "observations", rownames = FALSE, append = FALSE)
  RODBC::odbcClose(con)
  cat("\u2705 New accdb created: SOMEC_20260327.accdb\n")
} else {
  cat("\u26a0\ufe0f  Run on Windows to create the new .accdb file.\n")
}
