# ============================================================
# QC FIXES — SOMEC_20260321
# Generated by interactive_mission_qc_console.R
# ============================================================

# Load data before running fixes:
# source("interactive_mission_qc_console.R")


# ── AVI090806 | UNKNOWN_CATALOG | observations$activite [2026-03-21 13:32] ──
 observations <- observations |>
  mutate(
    activite = case_when(
      activite == "Vol" ~ "VOL",
      activite == "Eau" ~ "EAU",
      TRUE ~ activite
    )
  ) 
