# ============================================================
# FILE: qc_helpers.R
# PURPOSE: Shared helper functions for the interactive QC console.
#   Sourced by interactive_mission_qc_console.R after .lang and cfg are set.
# ============================================================

library(base64enc)

# ---- Fix script helpers -----------------------------------------------

.fixes_initialised <- FALSE
.modified_tables   <- character(0)

# Generate the opening block (load data from cache)
.make_opening_block <- function() {
  paste0(
    "# ============================================================\n",
    "# OPENING — load data\n",
    "# ============================================================\n\n",
    "library(tidyverse)\n",
    "library(janitor)\n",
    "library(RODBC)\n\n",
    "# Resolve repo root\n",
    ".repo_root <- tryCatch({\n",
    "  frames <- sys.frames()\n",
    "  ofiles <- Filter(Negate(is.null), lapply(frames, function(f) f$ofile))\n",
    "  if (length(ofiles) > 0) dirname(normalizePath(ofiles[[1]], mustWork = TRUE))\n",
    "  else dirname(normalizePath(rstudioapi::getSourceEditorContext()$path, mustWork = TRUE))\n",
    "}, error = function(e) getwd())\n\n",
    ".cache_dir <- file.path(.repo_root, \"GlobalContext\", \"_cache\")\n\n",
    "missions     <- readRDS(file.path(.cache_dir, \"missions.rds\"))\n",
    "transects    <- readRDS(file.path(.cache_dir, \"transects.rds\"))\n",
    "observations <- readRDS(file.path(.cache_dir, \"observations.rds\"))\n\n",
    "cat(\"\\u2705 Data loaded from cache.\\n\")\n\n",
    "# ============================================================\n",
    "# FIXES\n",
    "# ============================================================\n\n"
  )
}

# Generate the closing block (save RDS + create new accdb on Windows)
.make_closing_block <- function() {
  new_version <- paste0("SOMEC_", format(Sys.Date(), "%Y%m%d"))
  paste0(
    "\n# ============================================================\n",
    "# CLOSING — save updated RDS + create new accdb (Windows only)\n",
    "# ============================================================\n\n",
    "saveRDS(missions,     file.path(.cache_dir, \"missions.rds\"))\n",
    "saveRDS(transects,    file.path(.cache_dir, \"transects.rds\"))\n",
    "saveRDS(observations, file.path(.cache_dir, \"observations.rds\"))\n",
    "cat(\"\\u2705 Updated RDS files saved.\\n\")\n\n",
    "if (.Platform$OS.type == \"windows\") {\n",
    "  .gestion_root <- dirname(.repo_root)\n",
    "  .somec_root   <- dirname(.gestion_root)\n",
    "  .accdb_src    <- file.path(.somec_root, \"BaseDeDonnees\", \"", .accdb_version, ".accdb\")\n",
    "  .accdb_dst    <- file.path(.somec_root, \"BaseDeDonnees\", \"", new_version, ".accdb\")\n",
    "  file.copy(.accdb_src, .accdb_dst, overwrite = FALSE)\n",
    "  con <- RODBC::odbcConnectAccess2007(.accdb_dst, believeNRows = FALSE)\n",
    "  RODBC::sqlSave(con, missions,     tablename = \"missions\",     rownames = FALSE, append = FALSE)\n",
    "  RODBC::sqlSave(con, transects,    tablename = \"transects\",    rownames = FALSE, append = FALSE)\n",
    "  RODBC::sqlSave(con, observations, tablename = \"observations\", rownames = FALSE, append = FALSE)\n",
    "  RODBC::odbcClose(con)\n",
    "  cat(\"\\u2705 New accdb created: ", new_version, ".accdb\\n\")\n",
    "} else {\n",
    "  cat(\"\\u26a0\\ufe0f  Run on Windows to create the new .accdb file.\\n\")\n",
    "}\n"
  )
}

append_fix <- function(snippet, mission_id, issue_type, tbl, col) {

  # Track modified table
  .modified_tables <<- unique(c(.modified_tables, tbl))

  if (!.fixes_initialised) {
    start_fresh <- TRUE
    if (file.exists(.fixes_script)) {
      cat("\n\U0001F4C4 ", msg("fix_exists"), basename(.fixes_script), "\n")
      keep <- prompt(msg("keep_or_new"), c("k", "n"))
      start_fresh <- (keep == "n")
    } else {
      cat("\n\U0001F4C4 ", if (.lang == "f")
        paste0("Nouveau script de corrections : ", basename(.fixes_script), "\n")
      else
        paste0("New fix script: ", basename(.fixes_script), "\n"))
    }
    if (start_fresh && file.exists(.fixes_script)) file.remove(.fixes_script)

    # Ask whether to include opening data-loading block
    add_opening <- prompt(
      if (.lang == "f")
        "  Ajouter le bloc d'ouverture (chargement des donnees) ? [o]ui / [n]on > "
      else
        "  Add opening block (load data) to fixes script? [y]es / [n]o > ",
      if (.lang == "f") c("o", "n") else c("y", "n")
    )

    # Write header
    cat(
      "# ============================================================\n",
      "# ", msg("fix_header_title"), " \u2014 ", .accdb_version, "\n",
      "# Generated by interactive_mission_qc_console.R\n",
      "# ============================================================\n\n",
      file = .fixes_script, sep = "", append = FALSE
    )

    if (add_opening %in% c("y", "o")) {
      cat(.make_opening_block(), file = .fixes_script, append = TRUE)
    } else {
      cat(
        "# ", msg("fix_load_comment"), "\n",
        "# ============================================================\n",
        "# FIXES\n",
        "# ============================================================\n\n",
        file = .fixes_script, sep = "", append = TRUE
      )
    }

    .fixes_initialised <<- TRUE
  }

  # Build the fix entry
  header <- paste0(
    "\n# \u2500\u2500 ", mission_id, " | ", issue_type, " | ", tbl, "$", col,
    " [", format(Sys.time(), "%Y-%m-%d %H:%M"), "] \u2500\u2500\n"
  )
  fix_entry <- paste0(header, snippet, "\n")

  # Read existing file — check for closing block marker every time
  existing    <- if (file.exists(.fixes_script)) readLines(.fixes_script) else character(0)
  closing_idx <- which(startsWith(trimws(existing), "# CLOSING"))

  if (length(closing_idx) > 0) {
    # Insert fix BEFORE the closing block
    new_content <- c(
      existing[seq_len(closing_idx[1] - 1)],
      strsplit(fix_entry, "\n")[[1]],
      "",
      existing[closing_idx[1]:length(existing)]
    )
    writeLines(new_content, .fixes_script)
    cat("\u2192 ", if (.lang == "f")
      "Correction insérée avant le bloc de sauvegarde.\n"
    else
      "Fix inserted before closing block.\n")
  } else {
    cat(fix_entry, file = .fixes_script, append = TRUE)
  }

  cat("\u2705 ", msg("fix_appended"), basename(.fixes_script), "\n")

  # Always offer to add/replace closing block
  done <- prompt(
    if (.lang == "f")
      "  Terminer et ajouter le bloc de sauvegarde ? [o]ui / [n]on > "
    else
      "  Done? Add save + new accdb closing block? [y]es / [n]o > ",
    if (.lang == "f") c("o", "n") else c("y", "n")
  )
  if (done %in% c("y", "o")) {
    .strip_and_add_closing()
    cat(if (.lang == "f")
      "\u2705 Bloc de sauvegarde ajoute. Le script est pret a etre execute.\n"
    else
      "\u2705 Closing block added. Script is ready to run.\n")
  }
}

# Strip any existing closing block then append a fresh one
.strip_and_add_closing <- function() {
  existing    <- if (file.exists(.fixes_script)) readLines(.fixes_script) else character(0)
  closing_idx <- which(startsWith(trimws(existing), "# CLOSING"))
  if (length(closing_idx) > 0) {
    existing <- existing[seq_len(closing_idx[1] - 1)]
    writeLines(existing, .fixes_script)
  }
  cat(.make_closing_block(), file = .fixes_script, append = TRUE)
}

prompt <- function(msg_txt, valid = NULL) {
  repeat {
    ans <- readline(msg_txt)
    ans <- trimws(ans)
    if (is.null(valid) || ans %in% valid) return(ans)
    cat("Invalid choice. Try again.\n")
  }
}

# ---- Row display helpers -----------------------------------------------

show_rows_with_context <- function(df, col, flag_idx, n_context = 2) {
  n <- nrow(df)
  context_idx <- unique(unlist(lapply(flag_idx, function(i) {
    max(1, i - n_context):min(n, i + n_context)
  })))
  context_idx <- sort(context_idx)
  id_cols    <- intersect(c("mission", "id_transect", "id", "date", "heure", "site"), names(df))
  id_cols    <- setdiff(id_cols, col)
  other_cols <- setdiff(names(df), c(col, id_cols))
  df_show <- df[context_idx, ] |>
    select(all_of(c(col, id_cols, other_cols))) |>
    as_tibble() |>
    mutate(.flag = if_else(row_number() %in% which(context_idx %in% flag_idx), "<<", ""),
           .before = 1)
  invisible(df_show)
}

show_rows <- function(df, col) {
  id_cols    <- intersect(c("mission", "id_transect", "id", "date", "heure", "site"), names(df))
  id_cols    <- setdiff(id_cols, col)
  other_cols <- setdiff(names(df), c(col, id_cols))
  df_show <- df |>
    select(all_of(c(col, id_cols, other_cols))) |>
    as_tibble()
  invisible(df_show)
}

show_rows_for_day <- function(df, col, date_col = "date") {
  if (!date_col %in% names(df)) {
    cat("\u26a0\ufe0f ", msg("no_date_col"), "\n")
    return(invisible(NULL))
  }
  dates_available <- sort(unique(as.Date(df[[date_col]])))
  cat(msg("dates_available"), "\n")
  for (i in seq_along(dates_available)) {
    cat(sprintf("  [%d] %s\n", i, dates_available[i]))
  }
  choice <- readline(msg("date_prompt"))
  choice <- suppressWarnings(as.integer(trimws(choice)))
  if (is.na(choice) || choice < 1 || choice > length(dates_available)) {
    return(invisible(NULL))
  }
  selected_date <- dates_available[choice]
  day_rows <- df[as.Date(df[[date_col]]) == selected_date, ]
  df_shown <- show_rows(day_rows, col)
  cat(sprintf("\n%s %s (%d %s)\n",
      msg("all_rows_day"), selected_date, nrow(df_shown), msg("rows_label")))
  cat(if (.lang == "f")
    "\U0001F441  Inspectez le tableau dans le viewer a droite.\n"
  else
    "\U0001F441  Inspect the table in the viewer on your right.\n")
  view_in_viewer(df_shown, title = paste0(col, " \u2014 ", selected_date))
}

# ---- Viewer -----------------------------------------------

view_in_viewer <- function(df = NULL, title = "QC Table", plot_file = NULL) {
  tmp <- file.path(tempdir(), "qc_viewer.html")
  plot_html <- ""
  if (!is.null(plot_file) && file.exists(plot_file)) {
    b64 <- base64enc::base64encode(plot_file)
    plot_html <- paste0(
      "<div style='text-align:center;margin-bottom:12px;'>",
      "<img src='data:image/png;base64,", b64,
      "' style='max-width:400px;border:1px solid #ddd;border-radius:4px;'/>",
      "</div>"
    )
  }
  table_html <- ""
  if (!is.null(df) && nrow(df) > 0) {
    th <- paste0("<th>", names(df), "</th>", collapse = "")
    flag_col <- if (".flag" %in% names(df)) which(names(df) == ".flag") else NULL
    html_rows <- vapply(seq_len(nrow(df)), function(i) {
      is_flagged <- !is.null(flag_col) &&
        identical(as.character(df[[flag_col]][i]), "<<")
      row_style <- if (is_flagged) ' style="background:#fff3cd;"' else ""
      cells <- paste0("<td>", vapply(df[i, ], function(v)
        ifelse(is.na(v), "<span style='color:#aaa'>NA</span>", as.character(v)),
        character(1)), "</td>", collapse = "")
      paste0("<tr", row_style, ">", cells, "</tr>")
    }, character(1))
    table_html <- paste0(
      "<h4 style='margin:8px 0 4px;'>", title, " (", nrow(df), " rows)</h4>",
      "<div style='overflow-x:auto;'>",
      "<table><thead><tr>", th, "</tr></thead><tbody>",
      paste(html_rows, collapse = "\n"),
      "</tbody></table></div>"
    )
  }
  html <- paste0(
    "<!DOCTYPE html><html><head><meta charset='UTF-8'><style>",
    "body{font-family:monospace;font-size:12px;margin:8px;}",
    "table{border-collapse:collapse;width:100%;white-space:nowrap;}",
    "th{background:#4472C4;color:white;padding:4px 8px;text-align:left;position:sticky;top:0;}",
    "td{padding:3px 8px;border-bottom:1px solid #ddd;}",
    "tr:hover{background:#f0f0f0;}",
    "</style></head><body>",
    plot_html,
    table_html,
    "</body></html>"
  )
  writeLines(html, tmp, useBytes = TRUE)
  rstudioapi::viewer(tmp)
  invisible(NULL)
}

# ---- Other helpers -----------------------------------------------

print_dist <- function(x, top = 10) {
  tibble(value = as.character(x)) |>
    filter(!is.na(value)) |>
    count(value, sort = TRUE) |>
    mutate(pct = round(100 * n / sum(n), 1)) |>
    slice_head(n = top) |>
    print(n = Inf)
}

generate_recode_snippet <- function(table, col, map) {
  rules <- paste0(
    "      ", col, " == \"", names(map), "\" ~ \"", map, "\"",
    collapse = ",\n"
  )
  paste0(
    table, " <- ", table, " |>\n",
    "  mutate(\n",
    "    ", col, " = case_when(\n",
    rules, ",\n",
    "      TRUE ~ ", col, "\n",
    "    )\n",
    "  )"
  )
}

get_mission_bounds <- function(missions, mission_id) {
  row <- missions |> filter(.data[["mission"]] == mission_id) |> slice_head(n = 1)
  list(
    start = suppressWarnings(as.POSIXct(row$debut)),
    end   = suppressWarnings(as.POSIXct(row$fin))
  )
}

get_global_numeric_baseline <- function(global_ctx, table, column) {
  global_ctx$numeric_baselines |>
    filter(table == !!table, column == !!column) |>
    slice_head(n = 1)
}

load_access_table_cached <- function(accdb_path, table_name, cache_dir) {
  cache_file <- file.path(cache_dir, paste0(table_name, ".rds"))
  cache_exists <- file.exists(cache_file)
  accdb_exists <- !is.null(accdb_path) && file.exists(accdb_path)
  if (cache_exists && accdb_exists) {
    cache_mtime <- file.info(cache_file)$mtime
    accdb_mtime <- file.info(accdb_path)$mtime
    if (!is.na(cache_mtime) && !is.na(accdb_mtime) && cache_mtime >= accdb_mtime) {
      return(readRDS(cache_file))
    }
  }
  if (cache_exists && !accdb_exists) {
    message("\u26a0\ufe0f  '", basename(accdb_path %||% "accdb"), "' ",
            msg("no_accdb"), " ", msg("loading_cache"), " '", table_name, "'.")
    return(readRDS(cache_file))
  }
  if (!accdb_exists) {
    stop(
      "No cache found for '", table_name, "' and the .accdb is not accessible.\n",
      "Expected .accdb at: ", accdb_path, "\n",
      "Run the script on Windows to generate the .rds cache files."
    )
  }
  if (!exists("odbcConnectAccess2007", where = asNamespace("RODBC"), inherits = FALSE)) {
    stop("odbcConnectAccess2007 is not available on this platform (macOS).")
  }
  con <- RODBC::odbcConnectAccess2007(accdb_path, believeNRows = FALSE)
  on.exit(RODBC::odbcClose(con), add = TRUE)
  df <- RODBC::sqlFetch(con, table_name) |> clean_names()
  saveRDS(df, cache_file)
  message("\u2705  Cached '", table_name, "' to ", cache_file)
  df
}