# ============================================================
# QC FIXES — SOMEC_20260321
# Generated by interactive_mission_qc_console.R
# ============================================================

# Load data before running fixes:
# source("interactive_mission_qc_console.R")


# ── AVI090806 | NUMERIC_OUTLIER | transects$vagues [2026-03-21 16:25] ──
 transects <- transects |>
  mutate(
    vagues = if_else(mission == "AVI090806" & is.na(vagues),
      0.5, vagues)
  ) 

# ── AVI090806 | UNKNOWN_CATALOG | transects$site [2026-03-21 16:25] ──
 transects <- transects |>
  mutate(
    site = case_when(
      site == "Début" ~ "début",
      site == "Fin" ~ "fin",
      TRUE ~ site
    )
  ) 

# ── AVI090806 | UNKNOWN_CATALOG | transects$act_plateforme [2026-03-21 16:26] ──
 transects <- transects |>
  mutate(
    act_plateforme = case_when(
      act_plateforme == "EnDéplacement" ~ "Endéplacement",
      TRUE ~ act_plateforme
    )
  ) 

# ── AVI090806 | OUTSIDE_MISSION_DATES | transects$heure [2026-03-21 16:26] ──
 transects <- transects |>
  mutate(
    heure = if_else(
      mission == "AVI090806" &
      (heure < as.POSIXct("2009-08-06 00:00:00") |
       heure > as.POSIXct("2009-08-07 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(heure, "%H:%M:%S")), tz="UTC"),
      heure
    )
  ) 

# ── AVI090806 | OUTSIDE_MISSION_DATES | transects$date_heure [2026-03-21 16:27] ──
 transects <- transects |>
  mutate(
    date_heure = if_else(
      mission == "AVI090806" &
      (date_heure < as.POSIXct("2009-08-06 00:00:00") |
       date_heure > as.POSIXct("2009-08-07 23:59:59")),
      as.POSIXct(paste(as.Date(date), format(date_heure, "%H:%M:%S")), tz="UTC"),
      date_heure
    )
  ) 
